# environment.yml
name: wm-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.5.1
    - torchvision==0.20.1
    - torchaudio
    - transformers
    - python-dotenv
    - ipykernel
    - numpy
    - opencv-python
    - scikit-learn
    - tqdm
    - pillow
    - ultralytics
    - webdataset
